# -*- coding: utf-8 -*-
"""FAME

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C--0nfvZZkCQGyQJa8HbrNmcFsDLCI76
"""

def verifica_valenza_fame(fame_stringa: str) -> bool:
    #valenze massime degli atomi ammessi
    valenze={'C':4,
             'N':3,
             'O':2,
             'H':1,
             'F':1,
             'S':2
             }
    #valore numerico dei legami
    valore_legami={'-':1,
                   '=':2,
                   '#':3}
    #dizionari per memorizzare tipo di atomo e somma dei legami
    somma_legami={}
    tipo_atomi={}
    #stato del parsing
    ultimo_atomo=-1        #ultimo atomo letto nella catena principale
    id_corrente=0          #identificatore degli atomi
    legame_precedente=1      #legame implicito (singolo)
    legame_esplicito=False #indica se la stringa termina con un legame
    #gestione delle ramificazioni
    in_ramificazione=False
    ancora=-1              #atomo da cui parte la ramificazione

    i=0
    while i<len(fame_stringa):
        c=fame_stringa[i]
        #se il carattere è un simbolo di un atomo
        if c in valenze:
            #registrazione del nuovo atomo
            somma_legami[id_corrente]=0
            tipo_atomi[id_corrente]=c
            #determinazione dell’atomo a cui collegarsi
            if in_ramificazione:
                target=ancora
            elif ultimo_atomo!=-1:
                target=ultimo_atomo
            else:
                target=-1
            #aggiornamento dei legami se esiste un target
            if target!=-1:
                somma_legami[target]+=legame_precedente
                somma_legami[id_corrente]+=legame_precedente
            #aggiornamento dell’ultimo atomo solo nella catena principale
            if not in_ramificazione:
                ultimo_atomo=id_corrente
            #preparazione al prossimo atomo
            id_corrente+=1
            legame_precedente=1
            legame_esplicito=False

        #se il carattere è un simbolo di legame
        elif c in valore_legami:
            legame_precedente=valore_legami[c]
            legame_esplicito=True

        #se il carattere è il simbolo di inizio ramificazione
        elif c=='^':
            if ultimo_atomo==-1:
                return False
            in_ramificazione=True
            ancora=ultimo_atomo
            legame_precedente=1

        #se il carattere è il simbolo di fine ramificazione
        elif c=='&':
            if not in_ramificazione:
                return False
            in_ramificazione=False
            ancora=-1

        #se il carattere è un carattere non non ammesso
        else:
            return False
        i+=1
    #Controllo finale su legami o ramificazioni non chiuse
    if legame_esplicito or in_ramificazione:
        return False
    #Verifica che ogni atomo rispetti la propria valenza
    for i in somma_legami:
        if somma_legami[i]!=valenze[tipo_atomi[i]]:
            return False
    return True

#test di validazione
print(verifica_valenza_fame("H-O-H"))
print(verifica_valenza_fame("C^HHHHH&"))