# -*- coding: utf-8 -*-
"""Main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fahTS82Yjfas321MgYbpodrXEKw-zgYW
"""

#importo la funzione dal file FAME
from fame import verifica_valenza_fame

print(f"H-O-H: {verifica_valenza_fame('H-O-H')}")  #risultato atteso:True

print(f"C^HHHH&: {verifica_valenza_fame('C^HHHH&')}")  #risultato atteso: True

print(f"C^HHHHH&: {verifica_valenza_fame('C^HHHHH&')}")  #risultato atteso: False